apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app-deployment
  labels:
    name: consumer-app-deployment
    app: devops-lamayai
spec:
  replicas: 1
  selector:
    matchLabels:
      name: consumer-app-pod
      app: devops-lamayai
  template:
    metadata:
      name: consumer-app-pod
      labels:
        name: consumer-app-pod
        app: devops-lamayai
    spec:
      containers:
        - image: lamayai/consumer-app:latest
          name: consumer-app
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
