apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: devops-lamayai
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      name: es-port
  selector:
    name: elasticsearch-pod
    app: devops-lamayai

