apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    name: kafka-deployment
    app: devops-lamayai
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-pod
      app: devops-lamayai
  template:
    metadata:
      name: kafka-pod
      labels:
        name: kafka-pod
        app: devops-lamayai
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
          image: confluentinc/cp-kafka:latest
          name: kafka
          ports:
            - containerPort: 9093
              hostPort: 9093
      hostname: kafka
