apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
  labels:
    app: devops-lamayai
spec:
  type: ClusterIP
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    name: kafka-pod
    app: devops-lamayai
