apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: default
  labels:
    app: devops-lamayai
spec:
  type: NodePort
  ports:
    - port: 7474
      targetPort: 7474
      name: ui
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    name: neo4j-pod
    app: devops-lamayai
