apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
  labels:
    app: devops-lamayai
spec:
  type: ClusterIP
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    name: zookeeper-pod
    app: devops-lamayai
